### ISSUE TITLE
503 on git

### ISSUE THREAD

**Issue by wasgehthierab** [x86dev/docker-ttrss#15]
Hey,

I just restarted my container and saw in the logs this error:
`fatal: unable to access 'https://git.tt-rss.org/git/tt-rss.git/': The requested URL returned error: 503`

Is this related to https://discourse.tt-rss.org/t/rate-limiting-for-some-git-related-requests/32 ?
Do you have an idea to fix this?

Thx!

**Comment by x86dev** [comment]
Could be ...the URL should be correct though. I got a 503 as well sometimes when pulling from this URL. Not a script error I can fix for now I'd say.
