### ISSUE TITLE
update to php 7 broke af_zz_imgproxy

### ISSUE THREAD

**Issue by CorePoint** [x86dev/docker-ttrss#17]
The update broke the plugin because mime_content_type has been replaced with finfo_file.
It sure is a problem with ttrss, but i'm just letting you know.

**Comment by CorePoint** [comment]
got that a little bit wrong it wasn't really removed but it's deprecated.
I contacted the developer of ttrss on irc and he wants it to be reported on his forums and he is willing to change it (or he'll forget about it), i don't have time for right now, so maybe somebody else does it or i'll do it in some time.

**Comment by CorePoint** [comment]
Just for informational purposes, it wasn't even deprecated.
That was just an error in the PHP docs and has been fixed since then.

**Comment by x86dev** [comment]
Should be fixed with https://github.com/x86dev/docker-ttrss/commit/f412ec20116d33d6f9efecec8051fe017e0a84e7.
