### ISSUE TITLE
PHP: function mime_content_type() is missing

### ISSUE THREAD

**Issue by laimoncijus** [x86dev/docker-ttrss#22]
Hi,

On my installation I'm getting a startup error: 

`PHP function mime_content_type() is missing, try enabling fileinfo module.`

Seems that `php7-fileinfo` extension is missing. Installing it manually solves the issue.

**Comment by jcabillot** [comment]
Same problem, same solution

**Comment by TheLux83** [comment]
Silly Question.
I have the same problem like you two. But how do I enable php7-fileinfo manually?

**Comment by thiesschneider** [comment]
You can start the container and exec the container. Then install php7-fileinfo by `apk update` followed by `apk add php7-fileinfo` until this pullrequest is merged by @x86dev

**Comment by TheLux83** [comment]
Hey @thiesschneider . Thanks for the information! I had to restart the container after installation, but now it seems to run again :)

**Comment by thiesschneider** [comment]
This could also be a possible solution: https://discourse.tt-rss.org/t/unable-to-run-feed-update-daemon/630/9

**Comment by x86dev** [comment]
Should be fixed with https://github.com/x86dev/docker-ttrss/commit/f412ec20116d33d6f9efecec8051fe017e0a84e7

Thanks for pointing out!
