### ISSUE TITLE
SELF_URL_PATH configuration broken since today

### ISSUE THREAD

**Issue by languitar** [x86dev/docker-ttrss#39]
With [this commit](https://git.tt-rss.org/fox/tt-rss/commit/56e16a8d855dafa7ad28273b2720883dba67bcf4) the config file template has changed and the dist entry for `SELF_URL_PATH` now looks like:
```
define('SELF_URL_PATH', '%SELF_URL_PATH');
```
This isn't supported by the current `sed`-magic used to configure the file and hence ttrss doesn't start anymore after an upgrade.

**Comment by eric-pierce** [comment]
I ran into this same problem - it can be fixed by manually modifying config.php but is not persistent and upon container restart it will revert.

**Comment by Harvester57** [comment]
> I ran into this same problem - it can be fixed by manually modifying config.php but is not persistent and upon container restart it will revert.

Can't you just commit the change to your container ?

**Comment by eric-pierce** [comment]
@Harvester57 I don't want to modify the container as it would be over-written if/when a new version is pulled down from dockerhub.

I just created pull request #41 to resolve this issue. @x86dev please review!

**Comment by x86dev** [comment]
Should be fixed now by the patch from @eric-pierce, which just got merged into the tree.

**Comment by trammel** [comment]
As this affects the base image, could you release a new one on dockerhub please?

**Comment by x86dev** [comment]
It should auto-build over at Docker Hub here: https://hub.docker.com/repository/docker/x86dev/docker-ttrss/builds

Not sure why it didn't this time -- will keep an eye on it, but for now I've just triggered a manual build.

**Comment by bugwelle** [comment]
Pulled the latest image an hour ago. Everything works again. Thanks! 😄

**Comment by x86dev** [comment]
Cool, thanks for verifying!
