### ISSUE TITLE
Can we get a Variable for session timeout ?

### ISSUE THREAD

**Issue by P6g9YHK6** [x86dev/docker-ttrss#46]
SESSION_EXPIRE_TIME 
can we get a variable to change this ? it is very troublesome for someone like me that the timeout is so short as i am using 2FA.

**Comment by x86dev** [comment]
Should be doable IIRC -- please feel free to submit a pull request. Thanks!

**Comment by x86dev** [comment]
SESSION_COOKIE_LIFETIME probably will do it.

**Comment by P6g9YHK6** [comment]
Does not work for me

**Comment by P6g9YHK6** [comment]
Closing this issue as i changed to another docker image
