### ISSUE TITLE
Error on RaspberryPi 4

### ISSUE THREAD

**Issue by Loxbey** [x86dev/docker-ttrss#47]
Beginner here, i get this error message

> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

**Engine Ver:** 20.10.2 (API: 1.41)
**Raspi:** linux armv7l Raspbian GNU/Linux 10 (buster)
**Kernel Ver:** 5.10.6-v7l+

How do i get the right version?

**Comment by x86dev** [comment]
Currently only x86 (amd64) is supported as a platform. Feel free to contribute :-)
